name: solaris

services:
  app:
    build: ..
    container_name: solaris-app
    restart: unless-stopped
    networks:
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
